### ISSUE TITLE
Latest version published incorrectly

### ISSUE THREAD

**Issue by bs1180** [HubbleHQ/emotion-css-grid#13]
I think there's a problem with the latest version - the installed package is largely empty! There is only the license, package.json and README.md files.

Comparing `yarn info @hubble/emotion-css-grid@1.0.2 dist` and `yarn info @hubble/emotion-css-grid dist` I can see the fileCount goes from 10 to 3, which I'm guessing isn't intentional.

**Comment by simon360** [comment]
Thanks for the repotrt, @bs1180 - we've pushed a new version of this. Please let us know if it's still giving you trouble.
